[package]
name = "cauldron"
version = "0.1.0"
authors = ["Pablo Diego <pablodiegoss@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bincode = "1.0.0"
serde = "1.0.34"
serde_derive = "1.0.34"